// Generated by gencpp from file example/answer.msg
// DO NOT EDIT!


#ifndef EXAMPLE_MESSAGE_ANSWER_H
#define EXAMPLE_MESSAGE_ANSWER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace example
{
template <class ContainerAllocator>
struct answer_
{
  typedef answer_<ContainerAllocator> Type;

  answer_()
    : answer(0)  {
    }
  answer_(const ContainerAllocator& _alloc)
    : answer(0)  {
  (void)_alloc;
    }



   typedef int32_t _answer_type;
  _answer_type answer;





  typedef boost::shared_ptr< ::example::answer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::example::answer_<ContainerAllocator> const> ConstPtr;

}; // struct answer_

typedef ::example::answer_<std::allocator<void> > answer;

typedef boost::shared_ptr< ::example::answer > answerPtr;
typedef boost::shared_ptr< ::example::answer const> answerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::example::answer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::example::answer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::example::answer_<ContainerAllocator1> & lhs, const ::example::answer_<ContainerAllocator2> & rhs)
{
  return lhs.answer == rhs.answer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::example::answer_<ContainerAllocator1> & lhs, const ::example::answer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace example

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::example::answer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example::answer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example::answer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example::answer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example::answer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example::answer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::example::answer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "470a19a3f8e6b2cdb8f4d6ac8875463a";
  }

  static const char* value(const ::example::answer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x470a19a3f8e6b2cdULL;
  static const uint64_t static_value2 = 0xb8f4d6ac8875463aULL;
};

template<class ContainerAllocator>
struct DataType< ::example::answer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "example/answer";
  }

  static const char* value(const ::example::answer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::example::answer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 answer\n"
;
  }

  static const char* value(const ::example::answer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::example::answer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct answer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::example::answer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::example::answer_<ContainerAllocator>& v)
  {
    s << indent << "answer: ";
    Printer<int32_t>::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAMPLE_MESSAGE_ANSWER_H
